steps:
  frontend:
    image: node:20
    when:
      - event: [pull_request, push]
      - branch:
        include: [woodpecker-pipeline]
        exclude: ["renovate/*"]
    commands:
#      - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends make
#      - yarn install && cd docs/openapi && yarn install 
      - make frontend

  backend:
    image: rust:latest
    when:
      - event: [pull_request, push]
      - branch:
        include: [woodpecker-pipeline]
        exclude: ["renovate/*"]
    commands:
      - cargo --version
      - make cache-bust
      - cargo build
